###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/67471bdcbe4bac9a7fbe350c

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First post",
    "owner": "Gil",
    "content": "Hello World!"
}

###