###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Ron

###

GET http://localhost:3000/posts/674c5b42003fe3d656132b6e

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "1 post",
    "sender": "Ron",
    "content": "apple !"
}

###

PUT  http://localhost:3000/posts/67471be1be4bac9a7fbe350e
Content-Type: application/json

{
    "content": "new content"
}

###