###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?sender=Ron

###

GET http://localhost:3000/posts/674c61d430bafa729b47de63

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "1 post",
    "sender": "Ron",
    "content": "apple !"
}

###

PUT  http://localhost:3000/posts/674c5b33003fe3d656132b6a
Content-Type: application/json

{
    "content": "new content"
}

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "674c61d430bafa729b47de63",
    "sender": "ee",
    "content": "ba!!"
}

###

Get http://localhost:3000/comments

###

Get http://localhost:3000/comments?post_id=674c61d430bafa729b47de63

###